import { defineStore } from 'pinia'

export const useUnit39Store = defineStore('counter', () => {
  const unit39 = {
    id:39,
    title:'遅れて、すみません',
    vocabularies:[
      {
        id:1,
        name:'答えます',
        meaning:'回答',
        sentence:'この問題は私には答えられない'
      },
      {
        id:2,
        name:'倒れます',
        meaning:'倒塌',
        sentence:'地震でビルが倒れました'
      },
      {
        id:3,
        name:'通ります',
        meaning:'通過、過',
        sentence:'このバスは駅前を通りますか'
      },
      {
        id:4,
        name:'死にます',
        meaning:'死',
        sentence:'今日は暑くて死にそう'
      },
      {
        id:5,
        name:'びっくりします',
        meaning:'吃驚',
        sentence:'ニュースを聞いて、びっくりしました'
      },
      {
        id:6,
        name:'がっかりします',
        meaning:'失望',
        sentence:'富士山が見えなくて、がっかりしました'
      },
      {
        id:7,
        name:'安心します',
        meaning:'安心、放心',
        sentence:'電話をもらって、安心しました'
      },
      {
        id:8,
        name:'けんかします',
        meaning:'吵架、打架',
        sentence:'最近、母とよく喧嘩をする'
      },
      {
        id:9,
        name:'離婚します',
        meaning:'離婚',
        sentence:'3年前に離婚しました'
      },
      {
        id:10,
        name:'太ります',
        meaning:'胖',
        sentence:'あなたは太りましたか'
      },
      {
        id:11,
        name:'やせます',
        meaning:'瘦',
        sentence:'彼女は瘦せすぎてる'
      },
      {
        id:12,
        name:'複雑',
        meaning:'複雜',
        sentence:'そんな複雑な文は理解できません'
      },
      {
        id:13,
        name:'邪魔',
        meaning:'妨礙、打攪',
        sentence:'お忙しいところをお邪魔してすみません'
      },
      {
        id:14,
        name:'硬い',
        meaning:'硬、堅硬',
        sentence:'この物は石と同じように硬い'
      },
      {
        id:15,
        name:'軟らかい',
        meaning:'軟、柔軟',
        sentence:'そのセーターは手触りがとても柔らかい'
      },
      {
        id:16,
        name:'汚い',
        meaning:'髒、骯髒',
        sentence:'汚い手で食べちゃダメよ'
      },{
        id:17,
        name:'うれしい',
        meaning:'高興',
        sentence:'皆の仲間になれて嬉しいです'
      },
      {
        id:18,
        name:'悲しい',
        meaning:'悲傷',
        sentence:'そのドラマは悲しい物語です'
      },
      {
        id:19,
        name:'恥ずかしい',
        meaning:'害羞、不好意思',
        sentence:'日本語を話すのが恥ずかしいです'
      },{
        id:20,
        name:'首相',
        meaning:'首相',
        sentence:'首相が入院したのをしってうますか'
      },
      {
        id:21,
        name:'地震',
        meaning:'地震',
        sentence:'地震でうちが壊れました'
      },
      {
        id:22,
        name:'津波',
        meaning:'地震',
        sentence:'津波で友達を亡くしました'
      },
      {
        id:23,
        name:'台風',
        meaning:'颱風',
        sentence:'台風で木が倒れました'
      },
      {
        id:24,
        name:'雷',
        meaning:'雷',
        sentence:'今日は雷と雨がすごいです'
      },
      {
        id:25,
        name:'火事',
        meaning:'火災',
        sentence:'火事でデパートが焼けました'
      },
      {
        id:26,
        name:'事故',
        meaning:'事故',
        sentence:'事故があって、バスが遅れてしまいました'
      },
      {
        id:27,
        name:'ハイキング',
        meaning:'遠足、徒步旅行',
        sentence:'連休があるとハイキングにいきます'
      },
      {
        id:28,
        name:'お見合い',
        meaning:'相親',
        sentence:'今日、お見合いに行きます'
      },
      {
        id:29,
        name:'操作',
        meaning:'操作',
        sentence:'最近の車は操作が簡単ですね'
      },
      {
        id:30,
        name:'会場',
        meaning:'會場',
        sentence:'ホテルから会場までは歩いて10分です'
      },
      {
        id:31,
        name:'代',
        meaning:'~費',
        sentence:'先月の電話代がいくらかかったか、教えてください'
      },
      {
        id:32,
        name:'屋',
        meaning:'店',
        sentence:'その菓子屋の商品はほとんど売り切れていた'
      },
      {
        id:33,
        name:'フロント',
        meaning:'(飯店等的)櫃台、詢問處',
        sentence:'鍵はフロントにお返しください'
      },
      {
        id:34,
        name:'号室',
        meaning:'號房間',
        sentence:'5号室で会議を行いましょう'
      },
      {
        id:35,
        name:'タオル',
        meaning:'毛巾',
        sentence:'浴場にはハンドタオルだけ持って入れます'
      },
      {
        id:36,
        name:'せっけん',
        meaning:'肥皂、香皂',
        sentence:'このせっけんはとても良い香りがします'
      },
      {
        id:37,
        name:'大勢',
        meaning:'很多(人)',
        sentence:'どうして人が大勢並んでいるんですか'
      },
      {
        id:38,
        name:'お疲れさまでした',
        meaning:'您辛苦了',
        sentence:'お疲れさまでした、ゆっくり寝てください'
      },
      {
        id:39,
        name:'伺います',
        meaning:'去。/拜訪。(「いきます」的謙讓語)',
        sentence:'約束の時間にそちらに伺います'
      },
      {
        id:40,
        name:'途中で',
        meaning:'(在)途中、路上；半途',
        sentence:'マラソンの途中で気分が悪くなりました'
      },
      {
        id:41,
        name:'トラック',
        meaning:'卡車',
        sentence:'門のところにトラックが1台駐車している'
      },
      {
        id:42,
        name:'ぶつかります',
        meaning:'撞、碰',
        sentence:'交差点でトラックと車がぶつかって、バスが動かなかったんです'
      },
      {
        id:43,
        name:'大人',
        meaning:'大人、成年人',
        sentence:''
      },
      {
        id:44,
        name:'しかし',
        meaning:'但是',
        sentence:''
      },
      {
        id:45,
        name:'また',
        meaning:'還有、且',
        sentence:''
      },
      {
        id:46,
        name:'洋服',
        meaning:'西式服裝',
        sentence:''
      },
      {
        id:47,
        name:'西洋化します',
        meaning:'西化',
        sentence:''
      },
      {
        id:48,
        name:'合います',
        meaning:'適合、合適',
        sentence:''
      },
      {
        id:49,
        name:'今では',
        meaning:'現在',
        sentence:''
      },
      {
        id:50,
        name:'成人式',
        meaning:'成人禮',
        sentence:''
      },
      {
        id:51,
        name:'伝統的',
        meaning:'傳統的',
        sentence:''
      }
    ]
  }
  

  return { unit39 }
})
